version: '3.9'

services:
  app:
    image: docker-next-apollo-dev
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client/pages:/app/pages
      - ./client/components:/app/components
      - ./client/lib:/app/lib

  api:
    image: docker-faker-graphql-dev
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
