version: '3.9'

services:
  app:
    image: docker-nextjs-dev
    build:
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      NEXT_PUBLIC_GRAPHQL_API: http://localhost:5000
    ports:
      - 3000:3000
    volumes:
      - ./client/pages:/app/pages
      - ./client/components:/app/components
      - ./client/lib:/app/lib

  api:
    image: docker-graphql-dev
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
