name: Client code build and test
on:
  pull_request:
    paths-ignore:
      - "**.md"
jobs:
  build:
    name: Client code build
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node JS 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Yarn install, lint, build and test
        run: |
          cd client
          yarn install
          yarn lint
          yarn build
          yarn test
    env:
      GITHUB_TOKEN: ${{ github.token }}
